### PR TITLE
A few fixes

### PR DESCRIPTION
**Pull request by BnMcGn**
Hi Helmut,
I've made a few changes to get cl-react to load for me:
-Added an .asd file; didn't take the liberty of inserting your email address. Also, you haven't added a license. Are you good with something minimal like MIT or Apache?
-My system downcased the "React DOM" thing. "|React| _D-O-M" is admittedly ugly. You must have your readtable-case set differently than I do. Maybe that should be made explicit in psx.lisp.
-I'm not sure how you are getting your JS to your browser. A bunch of stuff in cl-react.lisp wouldn't compile until I wrapped it in (ps ...). I dumped the results in the *_cl-react-lib*\* var for inclusion in web pages. Feels kind of ugly. If you've got something better...
Ben

### CODE REVIEW

**Comment by helmutkian** [comment]
Hi there Ben,

Thanks for the pull request!

A few notes:
- I will go ahead and officially make the license MIT.
-  Wrapping definitions in `(PS #| ... |#)` and dumping it into a top-level variable works fine for me until a better solution comes along. 
- I have my `READTABLE-CASE` set to `:INVERT`. I can either make this explicit by setting the top-level `(READTABLE-CASE *READTABLE*)`, use the named-readtables package (https://github.com/melisgl/named-readtables) to provide a custom readtable, or I can modify the actual code. I'd prefer to use `(ps:chain |React| "DOM")` over `(ps:chain |React| *D-O-M)` though. This does yield equivalent but different JS syntax though (`React['DOM']` instead of `React.DOM`). I wish Parenscript had a way to directly inject JavaScript identifiers as strings rather than having do finesse the CL symbol -> JS identifier conversion.

Do you have any suggestions for that last point regarding the `READTABLE-CASE`? I'm open to any approach. Once we have that figured out, I will accept the pull request.

**Comment by BnMcGn** [comment]
Borrowing from this code:
https://github.com/lispnik/parenscript-react/blob/master/parenscript-react.lisp
Readtable-case can be set to :invert for the duration of the file. I'm not
sure that setting it back to :upcase at the end of the file is the right
thing to do. It might trash people's settings. I'll play around with that a
little.

Otherwise it's back to its neat and tidy original state and seems to be
working.

Ben

**Comment by helmutkian** [comment]
This seems to work just fine for me. I'm not entirely sure why in the example you linked to setting the `READTABLE-CASE` is done at read time.

``` common-lisp

(in-package #:cl-react)

(defvar *user-readtable-case* (readtable-case *readtable*))

(setf (readtable-case *readtable*) :invert)

;;; Rest of the file ...

(setf (readtable-case *readtable*) *user-readtable-case*)
```

**Comment by helmutkian** [comment]
Hi there, I am closing this pull request. Thank you for submitting it. I've used your good ideas for improving the library, including making it more easily buildable.

Please let me know if you have any further suggestions on how to improve the library.

**Pull request closed without merging**
